### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by RickKimball** [stnolting/neo430#3]
On page 39 of the NEO430.pdf, I think you meant to say "stack" where you have heap:

**3.1.2. Dynamic Memory**
The remaining memory – so the memory after the .data section until the end of the RAM – is used for the
dynamic data during run time. This data includes the stack and the heap. The **stack** grows from the end of the memory down to the end of the .data section. The heap grows from the end of the .data section up to the end of the memory. Make sure there is no collision between the heap and the stack when using dynmic
memory allocation!

**Comment by stnolting** [comment]
Thanks for the hint!
I have corrected that and I will update the documentary with the next commit.
