### ISSUE TITLE
Is it a pip-lined CPU design? Thanks, Mate.

### ISSUE THREAD

**Issue by Kiddinglife** [stnolting/neo430#5]

**Comment by stnolting** [comment]
Well, It depends on the definition of "pipelining"....
Basically, each instruction is split in several tiny micro instruction, but some of these micro instructions overlap (like moving data from the register file to a temporary ALU register while updating the PC).
So from my point of view, this architecture is a multi-cycle approach, where no overlapping of real assembler instructions is conducted.
Does this help you? ;)

**Comment by Kiddinglife** [comment]
It did help a lot, thx.
